micronaut:
  application:
    name: hwchat
datasources:
  default:
    url: jdbc:mysql://localhost:3306/testdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'welcome'
